import frappe
from frappe.utils import now_datetime


def create_events():
    # chapter name → docname (autoname format: "{chapter_name}-{chapter_type}")
    C = {
        "bangalore":   "FOSS United Bangalore-City Community",
        "mumbai":      "FOSS United Mumbai-City Community",
        "delhi":       "FOSS United Delhi-City Community",
        "chennai":     "FOSS United Chennai-City Community",
        "hyderabad":   "FOSS United Hyderabad-City Community",
        "pune":        "FOSS United Pune-City Community",
        "kolkata":     "FOSS United Kolkata-City Community",
        "jaipur":      "FOSS United Jaipur-City Community",
        "indore":      "FOSS United Indore-City Community",
        "nagpur":      "FOSS United Nagpur-City Community",
        "iitb":        "FOSS Club IIT Bombay-FOSS Club",
        "bits":        "FOSS Club BITS Pilani-FOSS Club",
        "nitt":        "FOSS Club NIT Trichy-FOSS Club",
        "vit":         "FOSS Club VIT Vellore-FOSS Club",
        "indiafoss":   "India FOSS-Conference",
        "fosshack":    "FOSS Hack-Conference",
        "pyconf":      "PyConf Hyderabad-Conference",
        "online":      "FOSS United Online-Virtual",
        "diaspora":    "FOSS United Diaspora-Virtual",
        "kde":         "KDE India-Virtual",
    }

    events = [

        # ── BANGALORE – City Community ─────────────────────────────────────
        {
            "chapter": C["bangalore"],
            "event_name": "Bengaluru FOSS Meetup — January 2026",
            "event_type": "Meet Up",
            "status": "Concluded",
            "is_published": 1,
            "event_start_date": "2026-01-25 10:00:00",
            "event_end_date":   "2026-01-25 13:00:00",
            "event_location": "HasGeek House, Domlur, Bangalore",
            "event_bio": "Monthly community meetup for Bangalore FOSS enthusiasts",
            "event_description": "<p>Our regular monthly meetup where members share what they've been building, hacking, and learning. Lightning talks, open discussions, and networking over chai.</p>",
            "event_permalink": "blr-meetup-jan-2026",
            "show_rsvp": 1,
            "show_photos": 1,
            "map_link": "https://maps.google.com/?q=HasGeek+House+Bangalore",
        },
        {
            "chapter": C["bangalore"],
            "event_name": "Bengaluru FOSS Meetup — February 2026",
            "event_type": "Meet Up",
            "status": "Concluded",
            "is_published": 1,
            "event_start_date": "2026-02-22 10:00:00",
            "event_end_date":   "2026-02-22 13:00:00",
            "event_location": "91springboard, Koramangala, Bangalore",
            "event_bio": "Monthly FOSS meetup — Feb edition",
            "event_description": "<p>February's meetup featured talks on Linux, open-source AI tools, and contributions to KDE. Great turnout with 60+ attendees!</p>",
            "event_permalink": "blr-meetup-feb-2026",
            "show_rsvp": 1,
            "show_photos": 1,
        },
        {
            "chapter": C["bangalore"],
            "event_name": "Bengaluru FOSS Meetup — March 2026",
            "event_type": "Meet Up",
            "status": "Live",
            "is_published": 1,
            "event_start_date": "2026-03-28 10:00:00",
            "event_end_date":   "2026-03-28 13:00:00",
            "event_location": "NIMHANS Convention Centre, Bangalore",
            "event_bio": "March monthly meetup — open to all",
            "event_description": "<p>This month's FOSS meetup in Bangalore covers Nix, open-source hardware, and a hands-on intro to contributing to Frappe. All skill levels welcome.</p>",
            "event_permalink": "blr-meetup-mar-2026",
            "show_rsvp": 1,
            "map_link": "https://maps.google.com/?q=NIMHANS+Convention+Centre+Bangalore",
        },
        {
            "chapter": C["bangalore"],
            "event_name": "BangaloreFOSS 2025",
            "event_type": "Conference",
            "status": "Concluded",
            "is_published": 1,
            "event_start_date": "2025-11-08 09:00:00",
            "event_end_date":   "2025-11-09 18:00:00",
            "event_location": "NIMHANS Convention Centre, Bangalore",
            "event_bio": "Annual city-level FOSS conference in Bangalore",
            "event_description": "<p>BangaloreFOSS 2025 brought together 800+ attendees, 40 speakers, and 20 exhibitors celebrating free and open-source software. Tracks covered systems, web, AI/ML, and community.</p>",
            "event_permalink": "bangalorefoss-2025",
            "show_speakers": 1,
            "show_schedule": 1,
            "show_cfp": 1,
            "show_photos": 1,
            "must_attend": 1,
        },
        {
            "chapter": C["bangalore"],
            "event_name": "Linux Installation Party — Bangalore",
            "event_type": "Linux Installation Party",
            "status": "Concluded",
            "is_published": 1,
            "event_start_date": "2025-12-06 10:00:00",
            "event_end_date":   "2025-12-06 17:00:00",
            "event_location": "Christ University, Bangalore",
            "event_bio": "Help your friends ditch Windows and install Linux!",
            "event_description": "<p>Bring your laptop, we'll help you install Linux. Volunteers on hand to assist with Ubuntu, Fedora, Debian and Arch. Free stickers and community vibes.</p>",
            "event_permalink": "blr-lip-dec-2025",
            "show_rsvp": 1,
        },

        # ── MUMBAI ─────────────────────────────────────────────────────────
        {
            "chapter": C["mumbai"],
            "event_name": "Mumbai FOSS Meetup — February 2026",
            "event_type": "Meet Up",
            "status": "Concluded",
            "is_published": 1,
            "event_start_date": "2026-02-21 11:00:00",
            "event_end_date":   "2026-02-21 14:00:00",
            "event_location": "Bombay Connect, Andheri East, Mumbai",
            "event_bio": "Monthly Mumbai FOSS community meetup",
            "event_description": "<p>Mumbai's FOSS community gathered for talks on open-source databases, privacy tools, and a discussion on FOSS contributions from Indian developers.</p>",
            "event_permalink": "mumbai-meetup-feb-2026",
            "show_rsvp": 1,
            "show_photos": 1,
        },
        {
            "chapter": C["mumbai"],
            "event_name": "MumbaiFOSS Workshop: Git & Open Source Contributions",
            "event_type": "Workshop",
            "status": "Concluded",
            "is_published": 1,
            "event_start_date": "2026-01-11 10:00:00",
            "event_end_date":   "2026-01-11 16:00:00",
            "event_location": "IIT Bombay, Powai, Mumbai",
            "event_bio": "Hands-on git workshop for beginners wanting to contribute to FOSS",
            "event_description": "<p>A full-day workshop covering Git basics, GitHub workflows, how to find beginner-friendly issues, and making your first open-source pull request. Laptops required.</p>",
            "event_permalink": "mumbai-git-workshop-jan-2026",
            "show_rsvp": 1,
        },
        {
            "chapter": C["mumbai"],
            "event_name": "Mumbai FOSS Meetup — March 2026",
            "event_type": "Meet Up",
            "status": "Live",
            "is_published": 1,
            "event_start_date": "2026-03-21 11:00:00",
            "event_end_date":   "2026-03-21 14:00:00",
            "event_location": "Maker's Asylum, Andheri, Mumbai",
            "event_bio": "March edition of Mumbai's monthly FOSS meetup",
            "event_description": "<p>This month we're focusing on open hardware, Raspberry Pi projects, and a lightning talk session. Register to join us!</p>",
            "event_permalink": "mumbai-meetup-mar-2026",
            "show_rsvp": 1,
            "map_link": "https://maps.google.com/?q=Makers+Asylum+Mumbai",
        },

        # ── DELHI ──────────────────────────────────────────────────────────
        {
            "chapter": C["delhi"],
            "event_name": "Delhi FOSS Meetup — December 2025",
            "event_type": "Meet Up",
            "status": "Concluded",
            "is_published": 1,
            "event_start_date": "2025-12-20 11:00:00",
            "event_end_date":   "2025-12-20 14:00:00",
            "event_location": "Delhivery HQ, Gurugram",
            "event_bio": "Year-end FOSS meetup in Delhi",
            "event_description": "<p>Year-end gathering of the Delhi FOSS community with retrospectives, demos, and plans for 2026.</p>",
            "event_permalink": "delhi-meetup-dec-2025",
            "show_rsvp": 1,
            "show_photos": 1,
        },
        {
            "chapter": C["delhi"],
            "event_name": "DelhiFOSS Birds of a Feather: Privacy & Digital Rights",
            "event_type": "Birds Of Feathers",
            "status": "Concluded",
            "is_published": 1,
            "event_start_date": "2026-01-17 15:00:00",
            "event_end_date":   "2026-01-17 18:00:00",
            "event_location": "IIT Delhi, Hauz Khas",
            "event_bio": "Informal discussion on privacy tools and digital rights",
            "event_description": "<p>A BoF session bringing together activists, developers, and policy folks to discuss open-source privacy tools, surveillance, and digital rights in India.</p>",
            "event_permalink": "delhi-bof-privacy-jan-2026",
        },
        {
            "chapter": C["delhi"],
            "event_name": "Delhi FOSS Meetup — April 2026",
            "event_type": "Meet Up",
            "status": "Draft",
            "is_published": 0,
            "event_start_date": "2026-04-18 11:00:00",
            "event_end_date":   "2026-04-18 14:00:00",
            "event_location": "TBD, New Delhi",
            "event_bio": "April meetup — details coming soon",
            "event_description": "<p>Our April meetup is being planned. Stay tuned for venue and speaker announcements on our Telegram channel.</p>",
            "event_permalink": "delhi-meetup-apr-2026",
            "show_rsvp": 0,
        },

        # ── CHENNAI ────────────────────────────────────────────────────────
        {
            "chapter": C["chennai"],
            "event_name": "Chennai FOSS Meetup — January 2026",
            "event_type": "Meet Up",
            "status": "Concluded",
            "is_published": 1,
            "event_start_date": "2026-01-24 10:00:00",
            "event_end_date":   "2026-01-24 13:00:00",
            "event_location": "IIT Madras Research Park, Chennai",
            "event_bio": "Monthly Chennai FOSS meetup",
            "event_description": "<p>Chennai's January FOSS meetup featured talks on GNU/Linux history, Tamil localization efforts, and a demo of open-source GIS tools.</p>",
            "event_permalink": "chennai-meetup-jan-2026",
            "show_rsvp": 1,
            "show_photos": 1,
        },
        {
            "chapter": C["chennai"],
            "event_name": "ChennaiPy & FOSS United Colab: Python Workshop",
            "event_type": "Workshop",
            "status": "Concluded",
            "is_published": 1,
            "event_start_date": "2026-02-14 09:30:00",
            "event_end_date":   "2026-02-14 17:30:00",
            "event_location": "Anna University, Guindy, Chennai",
            "event_bio": "Full-day Python workshop in collaboration with ChennaiPy",
            "event_description": "<p>A collaborative event with ChennaiPy covering Python packaging, publishing to PyPI, and contributing to open-source Python projects. Beginner-friendly.</p>",
            "event_permalink": "chennai-python-workshop-feb-2026",
            "show_rsvp": 1,
        },
        {
            "chapter": C["chennai"],
            "event_name": "Linux Installation Party — Chennai",
            "event_type": "Linux Installation Party",
            "status": "Live",
            "is_published": 1,
            "event_start_date": "2026-04-05 10:00:00",
            "event_end_date":   "2026-04-05 16:00:00",
            "event_location": "SSN College of Engineering, Chennai",
            "event_bio": "Get Linux installed on your machine with community help",
            "event_description": "<p>Students and community members are invited to get Linux (Ubuntu, Fedora, Debian) installed on their laptops. Experienced volunteers will guide you through the process.</p>",
            "event_permalink": "chennai-lip-apr-2026",
            "show_rsvp": 1,
        },

        # ── HYDERABAD ──────────────────────────────────────────────────────
        {
            "chapter": C["hyderabad"],
            "event_name": "Hyderabad FOSS Meetup — February 2026",
            "event_type": "Meet Up",
            "status": "Concluded",
            "is_published": 1,
            "event_start_date": "2026-02-28 11:00:00",
            "event_end_date":   "2026-02-28 14:00:00",
            "event_location": "T-Hub, Raidurgam, Hyderabad",
            "event_bio": "Monthly Hyderabad FOSS community meetup",
            "event_description": "<p>February meetup featured contributions to Wikimedia, a talk on open-source hardware, and lightning demos from community members.</p>",
            "event_permalink": "hyd-meetup-feb-2026",
            "show_rsvp": 1,
            "show_photos": 1,
        },
        {
            "chapter": C["hyderabad"],
            "event_name": "Hyderabad FOSS Meetup — March 2026",
            "event_type": "Meet Up",
            "status": "Live",
            "is_published": 1,
            "event_start_date": "2026-03-21 11:00:00",
            "event_end_date":   "2026-03-21 14:00:00",
            "event_location": "IIIT Hyderabad, Gachibowli",
            "event_bio": "March FOSS meetup in Hyderabad",
            "event_description": "<p>This month's agenda includes talks on Zulip, open-source LLMs, and a panel discussion on the state of FOSS in Telangana.</p>",
            "event_permalink": "hyd-meetup-mar-2026",
            "show_rsvp": 1,
        },
        {
            "chapter": C["hyderabad"],
            "event_name": "HydFOSS Mini Conference 2025",
            "event_type": "Conference",
            "status": "Concluded",
            "is_published": 1,
            "event_start_date": "2025-10-18 09:00:00",
            "event_end_date":   "2025-10-18 18:00:00",
            "event_location": "HICC, Novotel, Hyderabad",
            "event_bio": "Mini annual FOSS conference for Hyderabad community",
            "event_description": "<p>HydFOSS 2025 brought together 350 participants for a single-day deep-dive into open-source tools and communities. 20 talks across 3 tracks.</p>",
            "event_permalink": "hydfoss-mini-2025",
            "show_speakers": 1,
            "show_schedule": 1,
            "show_cfp": 1,
            "show_photos": 1,
        },

        # ── PUNE ───────────────────────────────────────────────────────────
        {
            "chapter": C["pune"],
            "event_name": "Pune FOSS Meetup — March 2026",
            "event_type": "Meet Up",
            "status": "Live",
            "is_published": 1,
            "event_start_date": "2026-03-28 11:00:00",
            "event_end_date":   "2026-03-28 14:00:00",
            "event_location": "Persistent Systems, Senapati Bapat Road, Pune",
            "event_bio": "Monthly Pune FOSS meetup — March edition",
            "event_description": "<p>Join us for talks on open-source ERP, Frappe framework internals, and a session on contributing to upstream projects. All experience levels welcome.</p>",
            "event_permalink": "pune-meetup-mar-2026",
            "show_rsvp": 1,
            "map_link": "https://maps.google.com/?q=Persistent+Systems+Pune",
        },
        {
            "chapter": C["pune"],
            "event_name": "PuneFOSS Hackathon 2025",
            "event_type": "Hackathon",
            "status": "Concluded",
            "is_published": 1,
            "event_start_date": "2025-09-20 09:00:00",
            "event_end_date":   "2025-09-21 18:00:00",
            "event_location": "Symbiosis International University, Pune",
            "event_bio": "24-hour open-source hackathon in Pune",
            "event_description": "<p>Teams of 2–4 competed to build or improve open-source projects over 24 hours. 18 teams participated, 3 winning projects were merged upstream.</p>",
            "event_permalink": "pune-hackathon-2025",
            "show_rsvp": 1,
            "show_photos": 1,
        },
        {
            "chapter": C["pune"],
            "event_name": "Pune FOSS Meetup — January 2026",
            "event_type": "Meet Up",
            "status": "Concluded",
            "is_published": 1,
            "event_start_date": "2026-01-25 11:00:00",
            "event_end_date":   "2026-01-25 14:00:00",
            "event_location": "CoWork Cafe, Kothrud, Pune",
            "event_bio": "January edition of Pune FOSS meetup",
            "event_description": "<p>New year kickoff meetup with member introductions, project demos, and plans for 2026 events in Pune.</p>",
            "event_permalink": "pune-meetup-jan-2026",
            "show_rsvp": 1,
            "show_photos": 1,
        },

        # ── KOLKATA ────────────────────────────────────────────────────────
        {
            "chapter": C["kolkata"],
            "event_name": "Kolkata FOSS Meetup — November 2025",
            "event_type": "Meet Up",
            "status": "Concluded",
            "is_published": 1,
            "event_start_date": "2025-11-29 11:00:00",
            "event_end_date":   "2025-11-29 14:00:00",
            "event_location": "IEM Campus, EM Bypass, Kolkata",
            "event_bio": "Monthly FOSS meetup in Kolkata",
            "event_description": "<p>November's meetup covered Bengali localization of GNOME, open-source tools in journalism, and FOSS advocacy in West Bengal.</p>",
            "event_permalink": "kolkata-meetup-nov-2025",
            "show_rsvp": 1,
            "show_photos": 1,
        },
        {
            "chapter": C["kolkata"],
            "event_name": "Kolkata FOSS Meetup — February 2026",
            "event_type": "Meet Up",
            "status": "Concluded",
            "is_published": 1,
            "event_start_date": "2026-02-28 11:00:00",
            "event_end_date":   "2026-02-28 14:00:00",
            "event_location": "Webel Bhavan, Salt Lake, Kolkata",
            "event_bio": "February monthly FOSS meetup in Kolkata",
            "event_description": "<p>Talks on open-source security tools, a walkthrough of the Kolkata FOSS community history, and project showcases.</p>",
            "event_permalink": "kolkata-meetup-feb-2026",
            "show_rsvp": 1,
        },
        {
            "chapter": C["kolkata"],
            "event_name": "KolkatFOSS 2026",
            "event_type": "Conference",
            "status": "Draft",
            "is_published": 0,
            "event_start_date": "2026-07-18 09:00:00",
            "event_end_date":   "2026-07-19 18:00:00",
            "event_location": "Science City, Kolkata",
            "event_bio": "Annual FOSS conference for Eastern India",
            "event_description": "<p>KolkatFOSS 2026 is being planned. This will be the largest annual open-source gathering in Eastern India. CFP and registration opening soon.</p>",
            "event_permalink": "kolkatafoss-2026",
            "show_cfp": 0,
        },

        # ── JAIPUR – Inactive chapter, historical events ───────────────────
        {
            "chapter": C["jaipur"],
            "event_name": "Jaipur FOSS Meetup — August 2024",
            "event_type": "Meet Up",
            "status": "Concluded",
            "is_published": 1,
            "event_start_date": "2024-08-24 11:00:00",
            "event_end_date":   "2024-08-24 14:00:00",
            "event_location": "Manipal University Jaipur",
            "event_bio": "Last active FOSS meetup in Jaipur",
            "event_description": "<p>This was the last meetup held by FOSS United Jaipur. The chapter is currently looking for new leads to continue the work.</p>",
            "event_permalink": "jaipur-meetup-aug-2024",
            "show_photos": 1,
        },

        # ── FOSS CLUBS ─────────────────────────────────────────────────────
        {
            "chapter": C["iitb"],
            "event_name": "IIT Bombay Linux Installation Fest 2026",
            "event_type": "Linux Installation Party",
            "status": "Concluded",
            "is_published": 1,
            "event_start_date": "2026-02-07 10:00:00",
            "event_end_date":   "2026-02-07 16:00:00",
            "event_location": "Student Activity Centre, IIT Bombay, Mumbai",
            "event_bio": "Annual Linux installation fest at IIT Bombay",
            "event_description": "<p>The FOSS Club at IIT Bombay hosted its annual install fest, helping 80+ students install Linux on their machines and get started with open-source development.</p>",
            "event_permalink": "iitb-install-fest-2026",
            "show_rsvp": 1,
            "show_photos": 1,
        },
        {
            "chapter": C["iitb"],
            "event_name": "FOSS Club IIT Bombay — GSoC Prep Workshop",
            "event_type": "Workshop",
            "status": "Concluded",
            "is_published": 1,
            "event_start_date": "2026-01-18 14:00:00",
            "event_end_date":   "2026-01-18 17:00:00",
            "event_location": "LC101, IIT Bombay",
            "event_bio": "How to crack Google Summer of Code — from IITB alumni who did it",
            "event_description": "<p>Past GSoC contributors from IIT Bombay share their experiences, walk through proposal writing, and advise on choosing the right organization. Q&A session included.</p>",
            "event_permalink": "iitb-gsoc-workshop-jan-2026",
            "show_rsvp": 1,
        },
        {
            "chapter": C["iitb"],
            "event_name": "IIT Bombay Open Source Hackathon 2026",
            "event_type": "Hackathon",
            "status": "Live",
            "is_published": 1,
            "event_start_date": "2026-04-11 09:00:00",
            "event_end_date":   "2026-04-12 18:00:00",
            "event_location": "Gymkhana, IIT Bombay",
            "event_bio": "36-hour on-campus open-source hackathon",
            "event_description": "<p>Build or meaningfully improve an open-source project in 36 hours. Teams of 2–5. Judging criteria: usefulness, code quality, and upstream potential. Prizes and certificates for winners.</p>",
            "event_permalink": "iitb-oss-hackathon-2026",
            "show_rsvp": 1,
            "must_attend": 1,
        },
        {
            "chapter": C["bits"],
            "event_name": "BITS Pilani FOSS Awareness Talk",
            "event_type": "Meet Up",
            "status": "Concluded",
            "is_published": 1,
            "event_start_date": "2025-09-13 15:00:00",
            "event_end_date":   "2025-09-13 17:00:00",
            "event_location": "Lecture Hall Complex, BITS Pilani",
            "event_bio": "Introduction to FOSS for first-year students",
            "event_description": "<p>An orientation session for new students covering what FOSS is, why it matters, how to get involved, and opportunities like GSoC, Outreachy, and LFX Mentorship.</p>",
            "event_permalink": "bits-foss-awareness-sep-2025",
            "show_rsvp": 1,
            "show_photos": 1,
        },
        {
            "chapter": C["bits"],
            "event_name": "BITS Pilani: Open Source Contribution Sprint",
            "event_type": "Hackathon",
            "status": "Live",
            "is_published": 1,
            "event_start_date": "2026-04-04 10:00:00",
            "event_end_date":   "2026-04-05 18:00:00",
            "event_location": "CS Department, BITS Pilani",
            "event_bio": "Weekend contribution sprint — pick an issue, ship a fix",
            "event_description": "<p>A focused weekend where students pick up open-source issues, get mentorship from club members, and submit pull requests. Issues pre-selected from beginner-friendly repos.</p>",
            "event_permalink": "bits-contrib-sprint-apr-2026",
            "show_rsvp": 1,
        },
        {
            "chapter": C["nitt"],
            "event_name": "NIT Trichy Linux Workshop",
            "event_type": "Workshop",
            "status": "Concluded",
            "is_published": 1,
            "event_start_date": "2026-01-31 09:30:00",
            "event_end_date":   "2026-01-31 16:30:00",
            "event_location": "Central Lecture Theatre, NIT Trichy",
            "event_bio": "Beginner to intermediate Linux skills workshop",
            "event_description": "<p>Hands-on workshop covering the Linux command line, shell scripting, package management, and setting up a developer environment. Open to all NIT Trichy students.</p>",
            "event_permalink": "nitt-linux-workshop-jan-2026",
            "show_rsvp": 1,
            "show_photos": 1,
        },
        {
            "chapter": C["nitt"],
            "event_name": "FOSS Club NIT Trichy — Birds of a Feather: Open Source Careers",
            "event_type": "Birds Of Feathers",
            "status": "Concluded",
            "is_published": 1,
            "event_start_date": "2026-02-20 17:00:00",
            "event_end_date":   "2026-02-20 19:00:00",
            "event_location": "Seminar Hall, NIT Trichy",
            "event_bio": "Informal chat on building a career in open source",
            "event_description": "<p>Alumni working at open-source companies and contributors share how FOSS contributions shaped their careers. Open discussion format.</p>",
            "event_permalink": "nitt-bof-careers-feb-2026",
        },
        {
            "chapter": C["vit"],
            "event_name": "VIT Vellore FOSS Meetup — March 2024",
            "event_type": "Meet Up",
            "status": "Concluded",
            "is_published": 1,
            "event_start_date": "2024-03-16 14:00:00",
            "event_end_date":   "2024-03-16 17:00:00",
            "event_location": "Tech Tower, VIT Vellore",
            "event_bio": "Last FOSS club meetup at VIT Vellore",
            "event_description": "<p>The final event organised by the VIT Vellore FOSS Club before the lead team graduated. The club is now seeking new leads.</p>",
            "event_permalink": "vit-meetup-mar-2024",
            "show_photos": 1,
        },

        # ── INDIA FOSS – Conference chapter ────────────────────────────────
        {
            "chapter": C["indiafoss"],
            "event_name": "India FOSS 4.0",
            "event_type": "Conference",
            "status": "Concluded",
            "is_published": 1,
            "event_start_date": "2025-08-02 09:00:00",
            "event_end_date":   "2025-08-03 18:00:00",
            "event_location": "NIMHANS Convention Centre, Bangalore",
            "event_bio": "India's largest annual open-source conference",
            "event_description": "<p>India FOSS 4.0 hosted 2000+ attendees, 80 speakers, and 50 exhibitors across 5 tracks — the biggest edition yet. Talks covered systems, AI/ML, legal, policy, and community.</p>",
            "event_permalink": "indiafoss-4",
            "show_speakers": 1,
            "show_schedule": 1,
            "show_cfp": 1,
            "show_photos": 1,
            "must_attend": 1,
        },
        {
            "chapter": C["indiafoss"],
            "event_name": "India FOSS 5.0",
            "event_type": "Conference",
            "status": "Live",
            "is_published": 1,
            "event_start_date": "2026-08-01 09:00:00",
            "event_end_date":   "2026-08-02 18:00:00",
            "event_location": "NIMHANS Convention Centre, Bangalore",
            "event_bio": "India FOSS 5.0 — CFP open now!",
            "event_description": "<p>India FOSS 5.0 is coming in August 2026. Submit your talk proposal, register as a volunteer, or reach out about exhibiting. CFP deadline: May 31, 2026.</p>",
            "event_permalink": "indiafoss-5",
            "show_speakers": 1,
            "show_cfp": 1,
            "show_schedule": 0,
            "must_attend": 1,
        },

        # ── FOSS HACK – Conference chapter ─────────────────────────────────
        {
            "chapter": C["fosshack"],
            "event_name": "FOSS Hack 4",
            "event_type": "Hackathon",
            "status": "Concluded",
            "is_published": 1,
            "event_start_date": "2025-03-08 09:00:00",
            "event_end_date":   "2025-03-09 18:00:00",
            "event_location": "Online + Multiple Localhost Cities",
            "event_bio": "India's premier open-source hackathon — 4th edition",
            "event_description": "<p>FOSS Hack 4 saw 400+ participants across 90 teams build and improve open-source projects over a weekend. 12 localhost venues across India.</p>",
            "event_permalink": "fosshack-4",
            "show_rsvp": 1,
            "show_photos": 1,
            "must_attend": 1,
        },
        {
            "chapter": C["fosshack"],
            "event_name": "FOSS Hack 5",
            "event_type": "Hackathon",
            "status": "Live",
            "is_published": 1,
            "event_start_date": "2026-03-01 09:00:00",
            "event_end_date":   "2026-03-28 18:00:00",
            "event_location": "Online + Multiple Localhost Cities",
            "event_bio": "FOSS Hack 5 — register your team now!",
            "event_description": "<p>FOSS Hack 5 is live! Register your team, pick an open-source project to hack on, and join us at a localhost venue or participate online. Prizes worth ₹5L up for grabs.</p>",
            "event_permalink": "fosshack-5",
            "show_rsvp": 1,
            "must_attend": 1,
            "livestream_link": "https://youtube.com/live/fosshack5",
        },
        {
            "chapter": C["fosshack"],
            "event_name": "FOSS Hack 5 — Open Check-in",
            "event_type": "Online",
            "status": "Live",
            "is_published": 1,
            "event_start_date": "2026-03-19 18:00:00",
            "event_end_date":   "2026-03-19 19:30:00",
            "event_location": "Online (Jitsi Meet)",
            "event_bio": "Weekly online check-in for FOSS Hack 5 participants",
            "event_description": "<p>Weekly open check-in for FOSS Hack 5 teams. Share progress, get unblocked, ask questions. Join via the Jitsi link.</p>",
            "event_permalink": "fosshack-5-checkin-1",
            "show_rsvp": 1,
            "livestream_link": "https://meet.jit.si/fosshack5",
        },

        # ── PYCONF HYDERABAD – Conference (Independent) ────────────────────
        {
            "chapter": C["pyconf"],
            "event_name": "PyConf Hyderabad 2025",
            "event_type": "Conference",
            "status": "Concluded",
            "is_published": 1,
            "event_start_date": "2025-12-07 09:00:00",
            "event_end_date":   "2025-12-08 18:00:00",
            "event_location": "IIIT Hyderabad, Gachibowli",
            "event_bio": "Hyderabad's annual Python conference — 2025 edition",
            "event_description": "<p>PyConf Hyderabad 2025 brought 600 Pythonistas together for two days of talks, workshops, and sprints. Tracks covered web, data science, and open-source tooling.</p>",
            "event_permalink": "pyconf-hyderabad-2025",
            "show_speakers": 1,
            "show_schedule": 1,
            "show_cfp": 1,
            "show_photos": 1,
            "must_attend": 1,
        },
        {
            "chapter": C["pyconf"],
            "event_name": "PyConf Hyderabad 2026",
            "event_type": "Conference",
            "status": "Draft",
            "is_published": 0,
            "event_start_date": "2026-12-05 09:00:00",
            "event_end_date":   "2026-12-06 18:00:00",
            "event_location": "TBD, Hyderabad",
            "event_bio": "PyConf Hyderabad 2026 — planning in progress",
            "event_description": "<p>Planning has begun for PyConf Hyderabad 2026. Watch this space for CFP, sponsorship, and registration announcements.</p>",
            "event_permalink": "pyconf-hyderabad-2026",
        },

        # ── VIRTUAL CHAPTER ────────────────────────────────────────────────
        {
            "chapter": C["online"],
            "event_name": "FOSS United Monthly Online Meetup — February 2026",
            "event_type": "Online",
            "status": "Concluded",
            "is_published": 1,
            "event_start_date": "2026-02-15 16:00:00",
            "event_end_date":   "2026-02-15 18:00:00",
            "event_location": "Online (Jitsi Meet)",
            "event_bio": "Monthly online gathering for the FOSS United community",
            "event_description": "<p>February's online meetup featured community updates, project demos, and a discussion on onboarding new FOSS contributors in India.</p>",
            "event_permalink": "online-meetup-feb-2026",
            "show_rsvp": 1,
            "livestream_link": "https://meet.jit.si/fossunited",
        },
        {
            "chapter": C["online"],
            "event_name": "FOSS United Monthly Online Meetup — March 2026",
            "event_type": "Online",
            "status": "Live",
            "is_published": 1,
            "event_start_date": "2026-03-22 16:00:00",
            "event_end_date":   "2026-03-22 18:00:00",
            "event_location": "Online (Jitsi Meet)",
            "event_bio": "Monthly online meetup — March edition",
            "event_description": "<p>Join us online for the March edition. This month: End of Windows 10 support and the Linux migration push, FOSS Hack 5 progress, and community intros.</p>",
            "event_permalink": "online-meetup-mar-2026",
            "show_rsvp": 1,
            "livestream_link": "https://meet.jit.si/fossunited-march",
        },
        {
            "chapter": C["diaspora"],
            "event_name": "FOSS United Diaspora Meetup — Q1 2026",
            "event_type": "Online",
            "status": "Concluded",
            "is_published": 1,
            "event_start_date": "2026-01-10 15:30:00",
            "event_end_date":   "2026-01-10 17:30:00",
            "event_location": "Online (Discord Stage)",
            "event_bio": "Quarterly meetup for Indian FOSS contributors living abroad",
            "event_description": "<p>Indians working on open source from outside India share updates, introduce themselves, and discuss how to stay connected with India's FOSS ecosystem.</p>",
            "event_permalink": "diaspora-meetup-q1-2026",
            "show_rsvp": 1,
        },

        # ── CANCELLED event ────────────────────────────────────────────────
        {
            "chapter": C["mumbai"],
            "event_name": "Mumbai FOSS Hackathon 2025 [CANCELLED]",
            "event_type": "Hackathon",
            "status": "Cancelled",
            "is_published": 1,
            "event_start_date": "2025-10-11 09:00:00",
            "event_end_date":   "2025-10-12 18:00:00",
            "event_location": "VJTI, Matunga, Mumbai",
            "event_bio": "Cancelled due to venue unavailability",
            "event_description": "<p>We regret that the Mumbai FOSS Hackathon 2025 has been cancelled due to unexpected venue unavailability. We will reschedule in 2026. All registered participants have been notified.</p>",
            "event_permalink": "mumbai-hackathon-2025-cancelled",
        },
    ]

    valid_fields = {f.fieldname for f in frappe.get_meta("FOSS Chapter Event").fields}

    created = skipped = 0
    for data in events:
        permalink = data.get("event_permalink")
        if frappe.db.exists("FOSS Chapter Event", {"event_permalink": permalink}):
            print(f"  SKIP  {data['event_name'][:60]}")
            skipped += 1
            continue

        clean = {k: v for k, v in data.items() if k in valid_fields or k == "doctype"}
        clean["doctype"] = "FOSS Chapter Event"

        doc = frappe.get_doc(clean)
        doc.insert(ignore_permissions=True)
        status_str = f"{doc.status:10s}"
        type_str   = f"{doc.event_type:25s}"
        print(f"  CREATE {status_str} | {type_str} | {doc.event_name[:55]}")
        created += 1

    frappe.db.commit()
    print(f"\nDone — {created} created, {skipped} skipped.")
