import frappe

def create_chapters():
    chapters = [
        # ── City Communities (Active) ──────────────────────────────────────
        {
            "doctype": "FOSS Chapter",
            "chapter_name": "FOSS United Bangalore",
            "chapter_type": "City Community",
            "chapter_status": "Active",
            "city": "Bangalore",
            "state": "Karnataka",
            "country": "India",
            "slug": "bangalore",
            "is_published": 1,
            "email": "bangalore@fossunited.org",
            "about_chapter": "<p>FOSS United Bangalore is the largest open-source community in South India, bringing together developers, designers, and enthusiasts passionate about free and open-source software.</p>",
            "telegram": "https://t.me/fossunitedbangalore",
            "x": "https://x.com/fossunitedbng",
            "linkedin": "https://linkedin.com/company/fossunited-bangalore",
            "discord": "https://discord.gg/fossunitedbangalore",
            "google_map_link": "https://maps.google.com/?q=Bangalore,Karnataka,India",
        },
        {
            "doctype": "FOSS Chapter",
            "chapter_name": "FOSS United Mumbai",
            "chapter_type": "City Community",
            "chapter_status": "Active",
            "city": "Mumbai",
            "state": "Maharashtra",
            "country": "India",
            "slug": "mumbai",
            "is_published": 1,
            "email": "mumbai@fossunited.org",
            "about_chapter": "<p>FOSS United Mumbai connects the vibrant open-source community in the financial capital of India. We host regular meetups, hackathons, and workshops.</p>",
            "telegram": "https://t.me/fossunitedmumbai",
            "x": "https://x.com/fossunitedmumbai",
            "whatsapp": "https://chat.whatsapp.com/fossunitedmumbai",
            "instagram": "https://instagram.com/fossunitedmumbai",
            "google_map_link": "https://maps.google.com/?q=Mumbai,Maharashtra,India",
        },
        {
            "doctype": "FOSS Chapter",
            "chapter_name": "FOSS United Delhi",
            "chapter_type": "City Community",
            "chapter_status": "Active",
            "city": "Delhi",
            "state": "Delhi (National Capital Territory of Delhi)",
            "country": "India",
            "slug": "delhi",
            "is_published": 1,
            "email": "delhi@fossunited.org",
            "about_chapter": "<p>FOSS United Delhi is the NCR's home for open-source enthusiasts. We organise events across Delhi-NCR to spread awareness and adoption of FOSS.</p>",
            "telegram": "https://t.me/fossuniteddelhi",
            "matrix": "https://matrix.to/#/#fossunited-delhi:matrix.org",
            "mastodon": "https://fosstodon.org/@fossuniteddelhi",
            "google_map_link": "https://maps.google.com/?q=New+Delhi,India",
        },
        {
            "doctype": "FOSS Chapter",
            "chapter_name": "FOSS United Chennai",
            "chapter_type": "City Community",
            "chapter_status": "Active",
            "city": "Chennai",
            "state": "Tamil Nadu",
            "country": "India",
            "slug": "chennai",
            "is_published": 1,
            "email": "chennai@fossunited.org",
            "about_chapter": "<p>FOSS United Chennai promotes free and open-source software in Tamil Nadu. We are a community of passionate contributors, learners, and advocates.</p>",
            "telegram": "https://t.me/fossunitedchennai",
            "x": "https://x.com/fossunitedmaa",
            "zulip": "https://fossunited.zulipchat.com/",
            "google_map_link": "https://maps.google.com/?q=Chennai,Tamil+Nadu,India",
        },
        {
            "doctype": "FOSS Chapter",
            "chapter_name": "FOSS United Hyderabad",
            "chapter_type": "City Community",
            "chapter_status": "Active",
            "city": "Hyderabad",
            "state": "Telangana",
            "country": "India",
            "slug": "hyderabad",
            "is_published": 1,
            "email": "hyderabad@fossunited.org",
            "about_chapter": "<p>FOSS United Hyderabad is the open-source hub of Cyberabad. We bring together technologists from across Hyderabad and Secunderabad.</p>",
            "telegram": "https://t.me/fossunitedhyd",
            "discord": "https://discord.gg/fossunitedhyd",
            "google_map_link": "https://maps.google.com/?q=Hyderabad,Telangana,India",
        },
        {
            "doctype": "FOSS Chapter",
            "chapter_name": "FOSS United Pune",
            "chapter_type": "City Community",
            "chapter_status": "Active",
            "city": "Pune",
            "state": "Maharashtra",
            "country": "India",
            "slug": "pune",
            "is_published": 1,
            "email": "pune@fossunited.org",
            "about_chapter": "<p>FOSS United Pune fosters open-source culture in the Oxford of the East. Join us for meetups, talks, and collaborative coding sessions.</p>",
            "telegram": "https://t.me/fossunitedpune",
            "x": "https://x.com/fossunitedpune",
            "linkedin": "https://linkedin.com/company/fossunited-pune",
            "google_map_link": "https://maps.google.com/?q=Pune,Maharashtra,India",
        },
        {
            "doctype": "FOSS Chapter",
            "chapter_name": "FOSS United Kolkata",
            "chapter_type": "City Community",
            "chapter_status": "Active",
            "city": "Kolkata",
            "state": "West Bengal",
            "country": "India",
            "slug": "kolkata",
            "is_published": 1,
            "email": "kolkata@fossunited.org",
            "about_chapter": "<p>FOSS United Kolkata champions open-source in the cultural capital of India, nurturing a thriving community of contributors and advocates.</p>",
            "telegram": "https://t.me/fossunitedkolkata",
            "facebook": "https://facebook.com/fossunitedkolkata",
            "google_map_link": "https://maps.google.com/?q=Kolkata,West+Bengal,India",
        },
        # ── City Community – Inactive ──────────────────────────────────────
        {
            "doctype": "FOSS Chapter",
            "chapter_name": "FOSS United Jaipur",
            "chapter_type": "City Community",
            "chapter_status": "Inactive",
            "city": "Jaipur",
            "state": "Rajasthan",
            "country": "India",
            "slug": "jaipur",
            "is_published": 1,
            "email": "jaipur@fossunited.org",
            "about_chapter": "<p>FOSS United Jaipur was a thriving community in the Pink City. Currently looking for new leads to revive activities.</p>",
            "telegram": "https://t.me/fossunitedjaipur",
            "google_map_link": "https://maps.google.com/?q=Jaipur,Rajasthan,India",
        },
        # ── City Community – New ───────────────────────────────────────────
        {
            "doctype": "FOSS Chapter",
            "chapter_name": "FOSS United Indore",
            "chapter_type": "City Community",
            "chapter_status": "New",
            "city": "Indore",
            "state": "Madhya Pradesh",
            "country": "India",
            "slug": "indore",
            "is_published": 0,
            "email": "indore@fossunited.org",
            "about_chapter": "<p>FOSS United Indore is our newest city chapter, recently formed by a group of passionate open-source enthusiasts in central India.</p>",
            "telegram": "https://t.me/fossunitedindore",
            "google_map_link": "https://maps.google.com/?q=Indore,Madhya+Pradesh,India",
        },
        # ── City Community – Defunct ───────────────────────────────────────
        {
            "doctype": "FOSS Chapter",
            "chapter_name": "FOSS United Nagpur",
            "chapter_type": "City Community",
            "chapter_status": "Defunct",
            "city": "Nagpur",
            "state": "Maharashtra",
            "country": "India",
            "slug": "nagpur",
            "is_published": 0,
            "email": "nagpur@fossunited.org",
            "about_chapter": "<p>FOSS United Nagpur was active between 2021 and 2023. The chapter has been disbanded and is no longer active.</p>",
            "google_map_link": "https://maps.google.com/?q=Nagpur,Maharashtra,India",
        },
        # ── FOSS Clubs (Active) ────────────────────────────────────────────
        {
            "doctype": "FOSS Chapter",
            "chapter_name": "FOSS Club IIT Bombay",
            "chapter_type": "FOSS Club",
            "chapter_status": "Active",
            "city": "Mumbai",
            "state": "Maharashtra",
            "country": "India",
            "slug": "foss-club-iit-bombay",
            "is_published": 1,
            "email": "fossclub@iitb.ac.in",
            "about_chapter": "<p>The FOSS Club at IIT Bombay promotes open-source culture among students. We run workshops, contribute to upstream projects, and participate in GSoC and Outreachy.</p>",
            "telegram": "https://t.me/fossclub_iitb",
            "discord": "https://discord.gg/fossclub-iitb",
            "x": "https://x.com/fossclub_iitb",
            "google_map_link": "https://maps.google.com/?q=IIT+Bombay,Powai,Mumbai",
        },
        {
            "doctype": "FOSS Chapter",
            "chapter_name": "FOSS Club BITS Pilani",
            "chapter_type": "FOSS Club",
            "chapter_status": "Active",
            "city": "Jaipur",
            "state": "Rajasthan",
            "country": "India",
            "slug": "foss-club-bits-pilani",
            "is_published": 1,
            "email": "fossclub@bits-pilani.ac.in",
            "about_chapter": "<p>FOSS Club at BITS Pilani encourages students to contribute to open-source and learn collaboratively through projects, hackathons, and talks.</p>",
            "telegram": "https://t.me/fossclubbitspilani",
            "github": "https://github.com/fossclub-bits",
            "google_map_link": "https://maps.google.com/?q=BITS+Pilani,Rajasthan",
        },
        {
            "doctype": "FOSS Chapter",
            "chapter_name": "FOSS Club NIT Trichy",
            "chapter_type": "FOSS Club",
            "chapter_status": "Active",
            "city": "Chennai",
            "state": "Tamil Nadu",
            "country": "India",
            "slug": "foss-club-nit-trichy",
            "is_published": 1,
            "email": "fossclub@nitt.edu",
            "about_chapter": "<p>The FOSS Club at NIT Trichy is a student-led initiative to promote free software usage, development, and advocacy in academic settings.</p>",
            "telegram": "https://t.me/fossclub_nitt",
            "discord": "https://discord.gg/fossclub-nitt",
            "google_map_link": "https://maps.google.com/?q=NIT+Trichy,Tamil+Nadu",
        },
        # ── FOSS Club – Inactive ───────────────────────────────────────────
        {
            "doctype": "FOSS Chapter",
            "chapter_name": "FOSS Club VIT Vellore",
            "chapter_type": "FOSS Club",
            "chapter_status": "Inactive",
            "city": "Chennai",
            "state": "Tamil Nadu",
            "country": "India",
            "slug": "foss-club-vit-vellore",
            "is_published": 1,
            "email": "fossclub@vit.ac.in",
            "about_chapter": "<p>FOSS Club VIT Vellore is currently looking for new student leads to take over and revive its activities.</p>",
            "telegram": "https://t.me/fossclub_vit",
            "google_map_link": "https://maps.google.com/?q=VIT+Vellore,Tamil+Nadu",
        },
        # ── Conference ─────────────────────────────────────────────────────
        {
            "doctype": "FOSS Chapter",
            "chapter_name": "India FOSS",
            "chapter_type": "Conference",
            "chapter_status": "Active",
            "country": "India",
            "slug": "indiafoss",
            "is_published": 1,
            "email": "indiafoss@fossunited.org",
            "about_chapter": "<p>India FOSS is the annual flagship conference of FOSS United, bringing together thousands of open-source enthusiasts, developers, and advocates from across India and the world.</p>",
            "x": "https://x.com/indiafoss",
            "mastodon": "https://fosstodon.org/@indiafoss",
            "telegram": "https://t.me/indiafoss",
            "linkedin": "https://linkedin.com/company/indiafoss",
            "youtube": "https://youtube.com/@indiafoss",
        },
        {
            "doctype": "FOSS Chapter",
            "chapter_name": "FOSS Hack",
            "chapter_type": "Conference",
            "chapter_status": "Active",
            "country": "India",
            "slug": "fosshack",
            "is_published": 1,
            "email": "fosshack@fossunited.org",
            "about_chapter": "<p>FOSS Hack is India's premier open-source hackathon, run by FOSS United. Teams collaborate to build or improve open-source tools over a weekend.</p>",
            "x": "https://x.com/fosshack",
            "telegram": "https://t.me/fosshack",
            "discord": "https://discord.gg/fosshack",
        },
        {
            "doctype": "FOSS Chapter",
            "chapter_name": "PyConf Hyderabad",
            "chapter_type": "Conference",
            "chapter_status": "Independent",
            "city": "Hyderabad",
            "state": "Telangana",
            "country": "India",
            "slug": "pyconf-hyderabad",
            "is_published": 1,
            "email": "pyconf@hyderabad.fossunited.org",
            "about_chapter": "<p>PyConf Hyderabad is an independent Python conference powered by the FOSS United community. It focuses on Python, its ecosystem, and open-source development.</p>",
            "x": "https://x.com/pyconfhyd",
            "telegram": "https://t.me/pyconfhyd",
            "mastodon": "https://fosstodon.org/@pyconfhyd",
            "google_map_link": "https://maps.google.com/?q=Hyderabad,Telangana,India",
        },
        # ── Virtual ────────────────────────────────────────────────────────
        {
            "doctype": "FOSS Chapter",
            "chapter_name": "FOSS United Online",
            "chapter_type": "Virtual",
            "chapter_status": "Active",
            "country": "India",
            "slug": "online",
            "is_published": 1,
            "email": "online@fossunited.org",
            "about_chapter": "<p>FOSS United Online is our virtual community for folks who prefer participating remotely. We host online meetups, live-streams, and collaborative sessions.</p>",
            "telegram": "https://t.me/fossunited",
            "matrix": "https://matrix.to/#/#fossunited:matrix.org",
            "discord": "https://discord.gg/fossunited",
            "x": "https://x.com/fossunited",
            "mastodon": "https://fosstodon.org/@fossunited",
            "zulip": "https://fossunited.zulipchat.com/",
        },
        {
            "doctype": "FOSS Chapter",
            "chapter_name": "FOSS United Diaspora",
            "chapter_type": "Virtual",
            "chapter_status": "Active",
            "country": "India",
            "slug": "diaspora",
            "is_published": 1,
            "email": "diaspora@fossunited.org",
            "about_chapter": "<p>FOSS United Diaspora is for Indian open-source enthusiasts living abroad. Connect, collaborate, and contribute from anywhere in the world.</p>",
            "telegram": "https://t.me/fossuniteddiaspora",
            "discord": "https://discord.gg/fossuniteddiaspora",
            "matrix": "https://matrix.to/#/#fossunited-diaspora:matrix.org",
        },
        # ── City Community – Independent ───────────────────────────────────
        {
            "doctype": "FOSS Chapter",
            "chapter_name": "KDE India",
            "chapter_type": "Virtual",
            "chapter_status": "Independent",
            "country": "India",
            "slug": "kde-india",
            "is_published": 1,
            "email": "india@kde.org",
            "about_chapter": "<p>KDE India is the Indian chapter of the KDE community, an affiliated independent group that promotes KDE software and contributes to its development.</p>",
            "telegram": "https://t.me/kdeindia",
            "matrix": "https://matrix.to/#/#kde-india:kde.org",
            "mastodon": "https://fosstodon.org/@kdeindia",
            "x": "https://x.com/kdeindia",
        },
    ]

    created = 0
    skipped = 0

    for data in chapters:
        slug = data.get("slug")
        if frappe.db.exists("FOSS Chapter", {"slug": slug}):
            print(f"  SKIP  {data['chapter_name']} (slug '{slug}' already exists)")
            skipped += 1
            continue

        # Remove non-doctype fields (e.g. github, youtube) gracefully
        valid_fields = {f.fieldname for f in frappe.get_meta("FOSS Chapter").fields}
        clean = {k: v for k, v in data.items() if k in valid_fields or k == "doctype"}

        doc = frappe.get_doc(clean)
        doc.insert(ignore_permissions=True)
        print(f"  CREATE {doc.chapter_type:15s} | {doc.chapter_status:12s} | {doc.chapter_name}")
        created += 1

    frappe.db.commit()
    print(f"\nDone — {created} created, {skipped} skipped.")
